# Generated by Django 3.2.3 on 2021-06-28 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_shouts_uploaddate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='MobileNo',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='userName',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
